### ISSUE TITLE
Banning and Moderating Students

### ISSUE THREAD

**Issue by mdeeb95** [vig9295/GroupFinder#28]
## Story/Task Details
- [x] Add UI for administrators to request to ban students
- [x] Update DB with banned student
- [x] Make sure the user is unable to login afterwards

## Acceptance Scenarios
Given: A user that will be banned
When: An admin deems the user has commited a violation
Then: The admin will send a request to have the student banned

## Done Done Criteria
Ensure that the students are being banned and unable to login afterwards.
