### ISSUE TITLE
Feedback from Users

### ISSUE THREAD

**Issue by mdeeb95** [vig9295/GroupFinder#32]
## Story/Task Details
- [x] Provide an option to allow suggestions to be given to different users and admin.
- [x] Users who are given feedback are given a notification
- [x] Admins receive emails

## Acceptance Scenarios
Given: An authenticated user goes to another user's page
When: The user attempts to give a suggestion to another person.
Then: The other person receives notification when that happens.

Given: An authenticated user is at his own page.
When: The user attempts to give some feedback to the app admins.
Then: The admins receives emails.

## Done Done Criteria
Ensure that the notifications are being sent in one way or the other, in case of users as notifications and otherwise as emails.
