### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by mdeeb95** [vig9295/GroupFinder#33]
## Story/Task Details
- [x] Provide UI for the user to be able to integrate with the calendar.
- [x] Create DB entry for users that have their calendar integrated.
- [x] User seeing and receiving updates for meetings they're part of.

## Acceptance Scenarios
Given: An authenticated user
When: The user attempts to integrate with his Android calendar.
Then: He receives a confirmation that the integration has been done and the DB is updated accordingly.

Given: A user with integrated calendar.
When: There is a meeting in the near future.
Then: He receives a reminder that he has to go that meeting with the details.

## Done Done Criteria
Users need to be able to receive automatic calendar additions which correspond with their meeting times. This will help with involve students more actively with their groups.
