### ISSUE TITLE
Piazza Integration

### ISSUE THREAD

**Issue by mdeeb95** [vig9295/GroupFinder#34]
## Story/Task Details
- [x] Provide an option to look for Piazza class with a similar class name
- [x] Create DB table that contains all the linked classes
- [x] Have a link to Piazza page for each class.

## Acceptance Scenarios
Given: A class with no Piazza integration
When: A user attempts to sign into Piazza
Then: A list with different Piazza classes are shown.

Given: A list of Piazza classes
When: A user attempts to integrate one class with Piazza
Then: The database is updated to add the piazza integration

## Done Done Criteria
Ensure that users are able to add and view Piazza classes to classes that they're enrolled for.
