### ISSUE TITLE
Globalize API calls

### ISSUE THREAD

**Issue by mdeeb95** [vig9295/GroupFinder#46]
## Story/Task Details
- [x] Update UI for meeting screen
- [x] Update Navigation UI in the chat screen
- [x] Consolidate all API calls

Update the UI for the meeting screen to be more intuitive and better looking. As well update the chat screen with navigation back to other parts of the applicaiton.

Have a singular js file with API call functions in order to be called by the controllers, as opposed to having large chunks of code repeated over all of the screens.
