### ISSUE TITLE
Group Permissions

### ISSUE THREAD

**Issue by Millu** [vig9295/GroupFinder#49]
## Story/Task Details
- [x] User can request to join a group they are not currently part of
- [x] Administrator can approve group requests 
- [x] Update group DB with request decision

## Acceptance Scenarios
Given: A user that is part of a class
When: A user requests to join a group
Then: The group creater will accept or reject the request

## Acceptance Scenarios
Given: A user that is part of a class
When: A user requests to join a group
Then: The group admin will accept or reject the request to join the group.

## Done Done Criteria
The user's request goes through and a decision is made.
